### ISSUE TITLE
[RFC] Formation of a community leads Telegram group

### ISSUE THREAD

**Issue by miccheng** [tech-community-singapore/rfcs#1]
# Proposal

Propose to start a telegram group for the community leads of tech meetup and chat groups.

### Purpose of Telegram Group

- Discuss issues that affect the whole tech community in Singapore.
- Support group for community organisers.

### Proposed Criteria for membership:

Telegram group shall have invite-only policy. Criteria for membership would be as follows:

- Founders, admins and core members of technology interest groups (meetups, chatrooms).
- Community Membership numbers of >500 (majority non-bots users).
- Continues to have active meetups (in the last 6 months prior to Circuit Breaker (7 April 2020)) or active chat discussions (in the last 2 weeks).

### Responsibilities of members in Telegram Group

- Vote on issues that affect the community in this RFC repository.
- Represent and advocate for the interest of your group in the whole of Singapore tech community stage.

## For Consultation

- [ ] Comments on the scope of the Telegram Group.
- [ ] Nominate community leads for inclusion in the Telegram Group.

## Closing Date

Date Time: 5pm, Monday 9 Nov 2020

**Comment by robertsky** [comment]
> Community Membership numbers of >500 (majority non-bots users).

What about fledging groups with small but active membership? These groups may or may not be new. 

Another issue that may come up over this group is when there are community issues with one or many meet up organisers as the focus of the discussion. Should these organisers recluse themselves from the discussions?

**Comment by miccheng** [comment]
> What about fledging groups with small but active membership? These groups may or may not be new.

The group size was to ensure that Telegram group members are representative of a segment in the larger Singapore tech community - that their opinion will carry weight. Without stats on the actual community population, 500 can feel arbitrary. Would you like to propose a different number? Or abolish this as a requirement?

> Should these organisers recluse themselves from the discussions?

We can make this as one of the items in Working Agreement of the Telegram Group. This will have to be voted on by the group once we form it. Possibly as a new RFC for public consultation.

**Comment by hhandoko** [comment]
Criteria sounds fair, however the Scala group haven't had any meetups in the last 6 months nor any chat group. Perhaps we can have the (criteria) review on a case-by-case basis?

**Comment by miccheng** [comment]
> Criteria sounds fair, however the Scala group haven't had any meetups in the last 6 months nor any chat group. Perhaps we can have the (criteria) review on a case-by-case basis?

I guess all the meetup groups are affected during the COVID-19 pandemic. So 6 months would be biased against groups that has not organized online meetup in a while (like the Scala group).

Amended to: **_"in the last 6 months prior to Circuit Breaker (7 April 2020)"_**

**Comment by valentine** [comment]
> Founders, admins and core members of technology interest groups (meetups, chatrooms).
> Community Membership numbers of >500 (majority non-bots users).

I don't think these criteria makes sense. There are founders and admins of some groups who get appointed because they're friends of the founders, or well-known in the community, or had a first-mover advantage, or maybe they're just _loud_ — but don't play an active role in the maintenance of the groups. Should they be considered "community leads"?

There are also smaller, tech-focused chat groups that have substantial discussion, but don't have a >500 membership and might not be known to the people in this thread.

Membership count also just means that whoever's involved in the chat group is good at marketing. From what I've observed of Telegram groups, a lot of people join and just lurk — it's possible that they're leaving the group chats unread, or that they don't use Telegram as one of their main communication channels. I am a member of some groups with >5,000 members, but it's always the same ~50 or so people talking.

All this also applies to Meetup.com groups. There is no barrier of entry to meetups — attendees are free to join to bump up the number of members, but that's not a good indication of how active a meetup actually is, because we all know there's that magical 50% dropout rate. 

Large numbers mainly suggest that the meetup has been around for ages; is, or has been, the tech-fad-of-the-year; or that the organisers were really good at marketing.

**Comment by miccheng** [comment]
@valentine What criteria do you suggest we use then?

**Comment by valentine** [comment]
Maybe _size shouldn't matter_.

If the intention of the group is to be open and inclusive, then it might be better for the process to be an open application, letting anyone interested in "being involved/heard" apply.

One field on the form would be a list of prior community contribution or involvement. Some reference-checking might be needed to ensure that an applicant isn't riding on the coattails of their other organisers.

**Comment by hazrulazhar** [comment]
> There are founders and admins of some groups who get appointed because they're friends of the founders, or well-known in the community, or had a first-mover advantage, or maybe they're just loud — but don't play an active role in the maintenance of the groups. Should they be considered "community leads"

I will agree that probably they're not community leads. It all boils down to how the main founder decides to recruit who can help. But I also think that invitation is not extended to any admin, but only the admin we recognise as the primary founder.

I suggest that it's probably easier to list down all the tech meetups and chats (whether they're on Telegram, Slack, Meetup or what have you) for us to identify collaboratively who those founder admins are, and extend that invitation to them.

**Comment by hazrulazhar** [comment]
> > Criteria sounds fair, however the Scala group haven't had any meetups in the last 6 months nor any chat group. Perhaps we can have the (criteria) review on a case-by-case basis?
> 
> I guess all the meetup groups are affected during the COVID-19 pandemic. So 6 months would be biased against groups that has not organized online meetup in a while (like the Scala group).
> 
> Amended to: **_"in the last 6 months prior to Circuit Breaker (7 April 2020)"_**

Also, some chats are private unless we are also inside. For example, DevSG is a private chat group. We kept it that way for privacy reasons and there are probably many out there that worked on the same premise. We would not know the exact numbers without asking for some kind of visual proof, and frankly that sounds like a bad idea. And because they're private, we wouldn't know how to evaluate those either without being invited in.

**Comment by miccheng** [comment]
A Telegram Group has been created to support the tech community organisers in Singapore.

Invite Link: https://t.me/joinchat/FqXs5GrCHbIyNGU1
